version: "3.8"

services:

  # --- Andmebaas ---
  db:
    image: pgduckdb/pgduckdb:18-v1.1.1
    container_name: iss-projekt-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT_HOST:-55432}:5432"
    volumes:
<<<<<<< HEAD
      - ./init:/docker-entrypoint-initdb.d   # SQL-skriptid, mis käivituvad esimesel korral
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-praktikum}"]
      interval: 10s
      retries: 5
      start_period: 5s
=======
      - iss_data:/app/data
    command: streamlit run app/app.py --server.address=0.0.0.0 --server.port=8501
    restart: always
>>>>>>> c2bfeba30c87ebc172981995d2835f905e89dfed

  # --- Töövoo konteiner (Python ETL skript) ---
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iss-projekt-pipeline
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    working_dir: /app
    tty: true

  # --- Näidikulaud (Streamlit) ---
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iss-projekt-dashboard
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${DASHBOARD_PORT_HOST:-8501}:8501"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    working_dir: /app
    command: ["streamlit", "run", "app/app.py", "--server.address=0.0.0.0"]

volumes:
  pgdata: